version: '3.9'
services:
  api:
    build: ./api
    environment:
      DATABASE_URL: ${DATABASE_URL:-sqlite:///./erp_gas.db}
      API_KEY: ${API_KEY}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  web:
    build: ./web
    environment:
      VITE_API_BASE: ${VITE_API_BASE}
      VITE_BRAND_NAME: ${VITE_BRAND_NAME}
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules   # <— evita que se pierdan deps
    command: sh -c "npm install && npm run dev -- --host"  # <— instala al arrancar
    depends_on:
      - api

volumes:
  web_node_modules:     # <— volumen nombrado
